DATA:
  IMG_SIZE: 448
  BATCH_SIZE: 8
MODEL:
  TYPE: dinov3 #swin
  NAME: mtlora_plus_dinov3vits_448_r16_scale4_pertask
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
  DINOV3:
    MODEL_NAME: vit_small
    PRETRAINED: /dinov3_weights/dinov3_vits16_pretrain_lvd1689m-08c60483.pth
  MTLORA:
    ENABLED: True
    R: [16, 16, 16, 16]
    SHARED_SCALE: [4.0]
    TASK_SCALE: [4.0]
    DROPOUT: [0.05, 0.05, 0.05, 0.05]
    TRAINABLE_SCALE_SHARED: False
    TRAINABLE_SCALE_PER_TASK: False
    INTERMEDIATE_SPECIALIZATION: False
    FREEZE_PRETRAINED: True
    SPLIT_QKV: False
    QKV_ENABLED: True
    PROJ_ENABLED: True
    FC1_ENABLED: True
    FC2_ENABLED: True
    DOWNSAMPLER_ENABLED: True
    R_PER_TASK:
      semseg: [4]
      classify: [4]
      detect: [4]
      count: [4]
      normals: [4]
      sal: [4]
      human_parts: [4]
      edge: [4]
      depth: [4]
      shared: [16]
  DECODER_HEAD:
    semseg: hrnet
    classify: simplenet
    detect: fcos
    count: pet
    normals: hrnet
    sal: hrnet
    human_parts: hrnet
    edge: hrnet
    depth: hrnet
TRAIN:
  ACCUMULATION_STEPS: 8
